# Generated by Django 5.2.1 on 2025-05-24 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GangReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('gang_name', models.CharField(help_text='If there’s no official name, write the name used locally.', max_length=100, verbose_name='What is the name of the gang?')),
                ('is_active', models.BooleanField(help_text='Check "Yes" if the gang is currently operating.', verbose_name='Is this gang still active?')),
                ('start_date', models.DateField(blank=True, help_text='Enter the approximate start date if known.', null=True, verbose_name='If known, when did this gang begin operating?')),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if the gang is still active or the date is unknown.', null=True, verbose_name='If known, when did this gang stop operating?')),
                ('main_area', models.CharField(help_text='(e.g., Cité Soleil, Martissant, Delmas 32, etc.)', max_length=255, verbose_name='Main neighborhood or area where this gang operates/operated?')),
                ('extra_areas', models.TextField(blank=True, help_text='Separate multiple areas with commas.', verbose_name='Additional places this gang controls or used to control (if any):')),
                ('department', models.CharField(choices=[('Ouest', 'Ouest'), ('Artibonite', 'Artibonite'), ('Nord', 'Nord'), ('Centre', 'Centre'), ('Grande-Anse', 'Grande-Anse'), ('Nippes', 'Nippes'), ('Nord-Est', 'Nord-Est'), ('Nord-Ouest', 'Nord-Ouest'), ('Sud', 'Sud'), ('Sud-Est', 'Sud-Est')], help_text='Select the department where the gang is/was most active.', max_length=50, verbose_name='Which department does this location belong to?')),
                ('activities', models.TextField(help_text='Be as specific as possible. (e.g., kidnappings, drug trafficking, extortion)', verbose_name='What kind of activities is/was the gang involved in?')),
                ('description', models.TextField(blank=True, help_text='Optional. Add any context or background details.', verbose_name='Describe the activities or key events involving this gang.')),
                ('rival_gangs', models.CharField(blank=True, help_text='List known rival gangs, if any.', max_length=255, verbose_name='Do you know of any rival gangs in the same area?')),
                ('sources', models.TextField(blank=True, help_text='(e.g., news report, local knowledge, eyewitness account, etc.)', verbose_name='Sources or references (if applicable):')),
                ('comments', models.TextField(blank=True, help_text='Any additional comments or observations?')),
                ('is_validated', models.BooleanField(default=False, help_text='Mark this report as validated before it appears on the website.', verbose_name='Validated for public display?')),
                ('parent', models.ForeignKey(blank=True, help_text='If this is an edit, link to the original report.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edits', to='core.gangreport', verbose_name='Parent report')),
            ],
            options={
                'db_table': 'gang_reports',
            },
        ),
    ]
