# Generated by Django 5.2.1 on 2025-05-24 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gangreport',
            name='extra_areas',
        ),
        migrations.CreateModel(
            name='ExtraArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Area name')),
                ('date_taken', models.DateField(blank=True, null=True, verbose_name='Date taken by the gang')),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if the gang is still active or the date is unknown.', null=True, verbose_name='If known, when did this gang stop operating in this area?')),
                ('notes', models.TextField(blank=True, verbose_name='Other relevant details about this area')),
                ('gang_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_areas', to='core.gangreport')),
            ],
            options={
                'verbose_name': 'Extra Area',
                'verbose_name_plural': 'Extra Areas',
            },
        ),
    ]
