# Generated by Django 5.2.1 on 2025-05-25 02:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_gangreport_extra_areas_extraarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='gangreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date Submitted'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gangreport',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Modified'),
        ),
    ]
