# Generated by Django 5.2.1 on 2025-05-25 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_gangreport_created_at_gangreport_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gangreport',
            name='comments',
            field=models.TextField(blank=True, help_text='Any additional comments or observations?', verbose_name='Some Comments'),
        ),
    ]
